{
  "openapi": "3.0.3",
  "info": {
    "title": "API de Verificação de Elegibilidade de Clientes",
    "description": "API para verificar a elegibilidade de clientes com base em critérios específicos.",
    "contact": {
      "name": "a equipe",
      "email": "tjbarbosa.sr@gmail.com"
    },
    "version": "0.0.1"
  },
  "servers": [
    {
      "url": "http://localhost:3000/"
    }
  ],
  "tags": [
    {
      "name": "Clientes",
      "description": "Clientes para elegibilidade",
      "externalDocs": {
        "description": "Veja mais detalhes",
        "url": "https://lemonenergy.notion.site/Teste-Backend-Lemon-Elegibilidade-9958a9678c0d4ac99185850fdb9716fc"
      }
    }
  ],
  "paths": {
    "/clientes/verificar-elegibilidade": {
      "post": {
        "tags": [
          "Clientes"
        ],
        "summary": "Valida a eligibilidade de um novo cliente",
        "description": "Nem todos os clientes que desejam fazer parte da Lemon podem ser aceitos no momento. Seja por razões regulatórias ou porque não vale a pena para o cliente ou para a Lemon ter essa empresa como cliente. No processo de aquisição de clientes, fazemos a checagem de elegibilidade da mesma, através dos dados contidos na conta de luz do cliente. Caso a empresa não seja elegível, precisamos explicitar os motivos para tal. Caso ela seja elegível, precisamos calcular também a projeção da quantidade de CO2 que ela deixaria de emitir caso usasse energia limpa.",
        "operationId": "verificar-elegibilidade",
        "requestBody": {
          "description": "Valida a eligibilidade de um novo cliente",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Elegibilidade"
              },
              "examples": {
                "Elegivel": {
                  "value": {
                    "numeroDoDocumento": "14041737706",
                    "tipoDeConexao": "bifasico",
                    "classeDeConsumo": "comercial",
                    "modalidadeTarifaria": "convencional",
                    "historicoDeConsumo": [
                      3878,
                      9760,
                      5976,
                      2797,
                      2481,
                      5731,
                      7538,
                      4392,
                      7859,
                      4160,
                      6941,
                      4597
                    ]
                  },
                  "summary": "Cliente elegivel"
                },
                "Inelegivel": {
                  "value": {
                    "numeroDoDocumento": "14041737706",
                    "tipoDeConexao": "bifasico",
                    "classeDeConsumo": "rural",
                    "modalidadeTarifaria": "verde",
                    "historicoDeConsumo": [
                      3878,
                      9760,
                      5976,
                      2797,
                      2481,
                      5731,
                      7538,
                      4392,
                      7859,
                      4160
                    ]
                  },
                  "summary": "Cliente inelegivel"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResultadoElegibilidade"
                },
                "examples": {
                  "Cliente elegível": {
                    "value": {
                      "elegivel": true,
                      "annualCO2Savings": "5553.2"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input",
            "content": {
              "application/json": {
                "examples": {
                  "Campos faltantes": {
                    "value": {
                      "numeroDoDocumento": "",
                      "tipoDeConexao": "bifasico",
                      "classeDeConsumo": "comercial",
                      "historicoDeConsumo": [
                        3878,
                        9760,
                        5976
                      ]
                    },
                    "summary": "Número documento e modalidade tarifaria faltantes"
                  },
                  "Campo TipoDeConexao inválido": {
                    "value": {
                      "numeroDoDocumento": "78324267050",
                      "tipoDeConexao": "quadrifasico",
                      "classeDeConsumo": "comercial",
                      "modalidadeTarifaria": "convencional",
                      "historicoDeConsumo": [
                        3878,
                        9760,
                        5976
                      ]
                    },
                    "summary": "Tipo de conexão inválido"
                  },
                  "O campo historicoDeConsumo não possui o número mínimo de itens": {
                    "value": {
                      "numeroDoDocumento": "78324267050",
                      "tipoDeConexao": "bifasico",
                      "classeDeConsumo": "comercial",
                      "modalidadeTarifaria": "convencional",
                      "historicoDeConsumo": [
                        3878
                      ]
                    },
                    "summary": "Histórico de consumo insuficiente"
                  },
                  "O campo historicoDeConsumo possui itens com valores inválidos": {
                    "value": {
                      "numeroDoDocumento": "78324267050",
                      "tipoDeConexao": "bifasico",
                      "classeDeConsumo": "comercial",
                      "modalidadeTarifaria": "convencional",
                      "historicoDeConsumo": [
                        0,
                        10000
                      ]
                    },
                    "summary": "Valores de histórico de consumo inválidos"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResultadoInelegibilidade"
                },
                "examples": {
                  "Campo classeDeConsumo não elegível": {
                    "value": {
                      "elegivel": false,
                      "razoesDeInelegibilidade": [
                        "Classe de consumo não elegível"
                      ]
                    },
                    "summary": "Classe de consumo não elegível"
                  },
                  "Campo modalidadeTarifaria não elegível": {
                    "value": {
                      "elegivel": false,
                      "razoesDeInelegibilidade": [
                        "Modalidade tarifária não elegível"
                      ]
                    },
                    "summary": "Modalidade tarifária não elegível"
                  },
                  "Campo historicoDeConsumo insuficiente": {
                    "value": {
                      "elegivel": false,
                      "razoesDeInelegibilidade": [
                        "Histórico de consumo insuficiente"
                      ]
                    },
                    "summary": "Histórico de consumo insuficiente"
                  },
                  "Consumo médio abaixo do mínimo necessário": {
                    "value": {
                      "elegivel": false,
                      "razoesDeInelegibilidade": [
                        "Consumo médio abaixo do mínimo necessário"
                      ]
                    },
                    "summary": "Consumo médio abaixo do mínimo necessário"
                  },
                  "Todas as exceções": {
                    "value": {
                      "elegivel": false,
                      "razoesDeInelegibilidade": [
                        "Classe de consumo não elegível",
                        "Modalidade tarifária não elegível",
                        "Histórico de consumo insuficiente",
                        "Consumo médio abaixo do mínimo necessário"
                      ]
                    },
                    "summary": "Todas as regras possíveis tratadas"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "examples": {
                  "Erro Interno do Servidor": {
                    "value": {
                      "error": "Ocorreu um erro interno"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Elegibilidade": {
        "type": "object",
        "properties": {
          "numeroDoDocumento": {
            "type": "string",
            "example": 78324267050
          },
          "tipoDeConexao": {
            "type": "string",
            "enum": [
              "monofasico",
              "bifasico",
              "trifasico"
            ],
            "example": "bifasico"
          },
          "classeDeConsumo": {
            "type": "string",
            "enum": [
              "residencial",
              "industrial",
              "comercial",
              "rural",
              "poderPublico"
            ],
            "example": "comercial"
          },
          "modalidadeTarifaria": {
            "type": "string",
            "enum": [
              "azul",
              "branca",
              "verde",
              "convencional"
            ],
            "example": "convencional"
          },
          "historicoDeConsumo": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 3,
            "minimum": 1,
            "maximum": 9999,
            "example": [
              3878,
              9760,
              5976
            ]
          }
        }
      },
      "ResultadoElegibilidade": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "elegivel": {
            "type": "string",
            "enum": [
              "true"
            ]
          },
          "economiaAnualDeCO2": {
            "type": "number",
            "minimum": 5555
          }
        },
        "required": [
          "elegivel",
          "economiaAnualDeCO2"
        ]
      },
      "ResultadoInelegibilidade": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "elegivel": {
            "type": "string",
            "enum": [
              "false"
            ]
          },
          "razoesDeInelegibilidade": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "string",
              "enum": [
                "Classe de consumo não elegível",
                "Modalidade tarifária não elegível",
                "Histórico de consumo insuficiente",
                "Consumo médio abaixo do mínimo necessário"
              ]
            }
          }
        },
        "required": [
          "elegivel",
          "razoesDeInelegibilidade"
        ]
      }
    }
  }
}
